/**
 * @description: Re-exports the shared contract types used by backend, Discord, and web.
 * @footnote-scope: interface
 * @footnote-module: ContractsIndex
 * @footnote-risk: low - Incorrect exports can cause type drift between packages.
 * @footnote-ethics: medium - Types document data meaning but do not execute logic.
 */

// This file stays small on purpose. Packages can import shared types from one
// place without needing to know the internal folder layout of the contracts
// package.

// Ethics Core contracts (provenance/risk metadata)
export type {
    Provenance,
    SafetyTier,
    SafetyRuleId,
    Citation,
    ExecutionStatus,
    ExecutionReasonCode,
    ToolInvocationName,
    ToolInvocationReasonCode,
    ReviewRuntimeLabel,
    ReviewRuntimeSummary,
    ToolInvocationIntent,
    ToolInvocationRequest,
    ToolExecutionContext,
    ContextIntegrationName,
    ContextStepRequest,
    ContextStepEvidence,
    ContextStepIntegrationContext,
    ContextStepExecutedResult,
    ContextStepFailedResult,
    ContextStepSkippedResult,
    ContextStepNeedsClarificationResult,
    ContextStepResult,
    CorrelationEnvelope,
    EvaluatorAuthorityLevel,
    EvaluatorDecisionMode,
    SafetyAction,
    SafetyReasonCode,
    SafetyEvaluationInput,
    SafetyEvaluationResult,
    SafetyDecision,
    EvaluatorOutcome,
    ExecutionEvent,
    StepSignalValue,
    StepSignals,
    WorkflowPlannerAction,
    WorkflowPlannerModality,
    WorkflowTerminalAction,
    WorkflowRoutingHintLane,
    WorkflowRoutingHintConflictResolution,
    WorkflowReviewParseFailureReason,
    WorkflowRoutingChainAttemptSignal,
    WorkflowRoutingChainSignals,
    WorkflowPlannerStepSignals,
    WorkflowAssessRoutingHintSignals,
    WorkflowToolClarificationSignals,
    WorkflowTerminalActionSignals,
    WorkflowRefinementSignals,
    WorkflowReviewParseFailureSignals,
    TraceAxisScore,
    PersonaExpressionStrength,
    PersonaExpressionSource,
    TraceFinalizationReasonCode,
    PartialResponseTemperament,
    ResponseTemperament,
    PresentationSettingName,
    PresentationSettingOmissionReasonCode,
    PresentationSettingsMetadata,
    TrustGraphMetadata,
    GitHubContextMetadata,
    GitHubContextReference,
    GitHubObjectReference,
    ProjectContextCategory,
    ProjectContextMatch,
    ProjectContextMetadata,
    ProjectContextReasonCode,
    ResponseMetadata,
    GenerationContextManifest,
    GenerationContextManifestEntry,
    GenerationContextManifestSource,
    GenerationContextManifestStatus,
    ResponseFootnote,
    ResponseFootnoteSection,
} from './policy/index.js';
export { RESPONSE_FOOTNOTE_SECTIONS } from './policy/index.js';
export { PROJECT_CONTEXT_CANONICAL_REPOSITORY } from './policy/index.js';
export {
    formatExecutionTimelineSummary,
    buildContextPresentationSummary,
    formatGitHubContextSummary,
    formatProjectContextSummary,
    deriveReviewRuntimeSummary,
    buildWorkflowRoutingChainSignals,
    buildWorkflowAssessRoutingHintSignals,
    buildWorkflowReviewParseFailureSignals,
    isPlannerFallbackStep,
    isRefinementGenerateStep,
    getWorkflowStepProfileIdSignal,
    getPlannerStepContractType,
} from './policy/index.js';
export {
    SafetyRuleIdSchema,
    SafetyActionSchema,
    SafetyReasonCodeSchema,
    SafetyDecisionSchema,
    PersonaExpressionStrengthSchema,
} from './policy/index.js';
export {
    SAFETY_RULE_METADATA,
    type SafetyRuleMetadata,
    CONTEXT_INTEGRATION_NAMES,
} from './policy/index.js';

// Web API contracts (request/response envelopes)
export type {
    ApiErrorResponse,
    NormalizedApiError,
    AuthenticatedPrincipal,
    GetAuthSessionResponse,
    ChatSurface,
    ChatTriggerKind,
    ChatAddressingParticipantKind,
    ChatAddressingRelation,
    ChatAddressingParticipant,
    ChatAddressingEvidence,
    ChatProfileOption,
    ChatConversationMessage,
    ChatAttachment,
    ChatCapabilities,
    ChatImageRequest,
    PostChatRequest,
    ChatMessageActionResponse,
    ChatReactActionResponse,
    ChatIgnoreActionResponse,
    ChatImageActionResponse,
    PostChatResponse,
    GetChatProfilesResponse,
    InternalImageAnnotations,
    InternalImageBackground,
    InternalImageChannelContext,
    InternalImageErrorEvent,
    InternalImageGenerationArtifact,
    InternalImagePartialImageEvent,
    InternalImageQuality,
    InternalImageRenderModel,
    InternalImageResultEvent,
    InternalImageSize,
    InternalImageStreamEvent,
    InternalImageTextModel,
    InternalImageUserContext,
    PostInternalImageGenerateRequest,
    PostInternalImageGenerateResponse,
    PostInternalImageRequest,
    PostInternalImageResponse,
    PostInternalImageDescriptionTaskRequest,
    PostInternalImageDescriptionTaskResponse,
    PostTracesRequest,
    PostTracesResponse,
    GetTraceResponse,
    GetTraceStaleResponse,
    ResponseCandidateStage,
    ResponseCandidate,
    GetResponseVersionsResponse,
    GetResponseVersionsStaleResponse,
    GetRuntimeConfigResponse,
} from './web/index.js';

// Internal voice contracts (tts + realtime)
export type {
    InternalTtsCosts,
    InternalTtsModel,
    InternalTtsOptions,
    InternalTtsUsage,
    InternalTtsVoice,
    InternalVoiceChannelContext,
    InternalVoiceOutputFormat,
    InternalVoiceParticipant,
    InternalVoiceRealtimeClientEvent,
    InternalVoiceRealtimeOptions,
    InternalVoiceRealtimeServerEvent,
    InternalVoiceSessionContext,
    PostInternalVoiceTtsRequest,
    PostInternalVoiceTtsResponse,
} from './voice/index.js';

// Workflow contracts
export type {
    ResultRef,
    Step,
    StepActivity,
    StepOutput,
    Workflow,
} from './workflow.js';

// Shared AI/provider vocabulary
export type {
    ConfiguredProviderModel,
    InternalImageRenderModelId,
    InternalImageTextModelId,
    InternalTtsModelId,
    InternalTtsVoiceId,
    SupportedBotInteractionAction,
    SupportedEngagementIgnoreMode,
    SupportedImageOutputFormat,
    SupportedLogLevel,
    SupportedOpenAIImageModel,
    SupportedOpenAIRealtimeModel,
    SupportedOpenAITextModel,
    SupportedOpenAITtsModel,
    SupportedOpenAITtsVoice,
    SupportedProvider,
    SupportedProviderModel,
    SupportedReasoningEffort,
    SupportedVerbosity,
} from './providers.js';
export { supportedReasoningEfforts } from './providers.js';
export type {
    ModelCostClass,
    ModelLatencyClass,
    ModelProfile,
    ModelProfileCapabilities,
    ModelProfileProviderRouting,
    PresentationGenerationSettings,
    PresentationPromptVariant,
    PresentationSamplingControl,
    WorkflowModeProfileId,
    WorkflowModelStepKind,
    StepRoutingEntry,
    StepRoutingModeMap,
    StepRoutingChainsConfig,
    ModelTierAlias,
} from './model-profiles.js';
export {
    ModelProfileCapabilitiesSchema,
    ModelProfileProviderRoutingSchema,
    ModelProfileCatalogSchema,
    ModelProfileSchema,
    PresentationGenerationSettingsSchema,
    WorkflowModeProfileIdSchema,
    WorkflowModelStepKindSchema,
    StepRoutingEntrySchema,
    StepRoutingModeMapSchema,
    StepRoutingChainsConfigSchema,
    modelCostClasses,
    modelLatencyClasses,
    modelTierAliases,
    presentationPromptVariants,
    presentationSamplingControls,
} from './model-profiles.js';

// Shared pricing vocabulary and pure cost helpers
export type {
    EffectiveImageGenerationQuality,
    EffectiveImageGenerationSize,
    ExplicitlyUnpricedOpenAITextModel,
    GPT5ModelType,
    ImageGenerationCostEstimate,
    ImageGenerationCostOptions,
    ImageGenerationQuality,
    ImageGenerationSize,
    ImageModelPricingKey,
    OmniModelType,
    ModelPricingCoverageClassification,
    ModelProfileTextPricingCoverage,
    OpenAIModelCanonicalizationResult,
    OpenAIModelCanonicalizationRule,
    OpenAITextCostAppliedRule,
    OpenAITextCostBreakdown,
    OpenAITextCostCompleteness,
    OpenAITextCostEstimate,
    OpenAITextCostIncompleteReason,
    OpenAITextUsageDetails,
    OpenAITtsCostBreakdown,
    OpenAIModelPricingResolution,
    OpenAITextPricingEntry,
    PricedOpenAITextModel,
    SupportedOpenAIEmbeddingModel,
    TextModelPricingKey,
} from './pricing.js';
export {
    canonicalizeOpenAIModelIdForPricing,
    classifyModelProfileTextPricingCoverage,
    estimateOpenAIImageGenerationCost,
    estimateOpenAIRealtimeCost,
    estimateOpenAITextCost,
    estimateOpenAITtsCost,
    hasOpenAIImagePricing,
    hasOpenAIRealtimePricing,
    hasOpenAITextPricing,
    hasOpenAITtsPricing,
    openAIImageGenerationPricingTable,
    openAIRealtimePricingTable,
    openAITextPricingTable,
    openAITtsPricingTable,
    explicitlyUnpricedOpenAITextModels,
    resolveOpenAIImagePricingModel,
    resolveOpenAIRealtimePricingModel,
    resolveOpenAITextPricingModel,
    resolveOpenAITtsPricingModel,
    resolveEffectiveImageGenerationQuality,
    resolveEffectiveImageGenerationSize,
    supportedOpenAIEmbeddingModels,
    supportedPricedOpenAITextModels,
} from './pricing.js';

// Shared planner/search hint vocabularies
export type { ChatRepoSearchHint } from './chat-search-hints.js';
export {
    chatRepoSearchHints,
    chatTopicHintQueryTerms,
} from './chat-search-hints.js';

export {
    createRuntimeLifecycleEvent,
    type RuntimeIdentity,
    type RuntimeLifecycleEvent,
    type RuntimeLifecycleEventName,
    type RuntimeLifecyclePhase,
    type RuntimeReadinessBoundary,
    type RuntimeService,
} from './logging.js';
