/**
 * @description: policy contract exports for provenance and response metadata.
 * @footnote-scope: interface
 * @footnote-module: EthicsCoreContractsIndex
 * @footnote-risk: low - Export mistakes can misalign types across packages.
 * @footnote-ethics: medium - Types document data meaning but do not execute logic.
 */

// This file is intentionally small. It re-exports shared policy types and
// runtime helpers (for example, formatExecutionTimelineSummary) so every
// package can import from one place.

export type {
    Provenance,
    ProvenanceSignals,
    SafetyTier,
    SafetyRuleId,
    Citation,
    ProvenanceAssessment,
    TraceAxisScore,
    TraceTemperamentAxisKey,
    TraceFinalizationReasonCode,
    ResponseTemperament,
    PartialResponseTemperament,
    ExecutionStatus,
    ExecutionReasonCode,
    PlannerExecutionReasonCode,
    PlannerExecutionPurpose,
    PlannerExecutionContractType,
    PlannerExecutionApplyOutcome,
    EvaluatorExecutionReasonCode,
    GenerationExecutionReasonCode,
    ToolInvocationName,
    ToolInvocationReasonCode,
    ToolInvocationIntent,
    ToolInvocationRequest,
    ToolExecutionContext,
    ContextStepRequest,
    ContextPromptMessage,
    ContextStepIntegrationContext,
    ContextStepExecutedResult,
    ContextStepFailedResult,
    ContextStepSkippedResult,
    ContextStepNeedsClarificationResult,
    ContextStepResult,
    ToolClarification,
    ToolClarificationOption,
    CorrelationEnvelope,
    ExecutionEventKind,
    PlannerExecutionEvent,
    EvaluatorExecutionEvent,
    ToolExecutionEvent,
    GenerationExecutionEvent,
    PresentationOutcome,
    PresentationReasonCode,
    PresentationAuditOutcome,
    PresentationAuditFailureCategory,
    PresentationMetadata,
    WorkflowStepStatus,
    WorkflowStepKind,
    WorkflowTerminationReason,
    WorkflowLimitKey,
    WorkflowLimitState,
    WorkflowEffectiveLimit,
    WorkflowLimitStop,
    StepSignalValue,
    StepSignals,
    WorkflowPlannerAction,
    WorkflowPlannerModality,
    WorkflowTerminalAction,
    WorkflowRoutingHintLane,
    WorkflowRoutingHintConflictResolution,
    WorkflowReviewParseFailureReason,
    WorkflowRoutingChainAttemptSignal,
    WorkflowRoutingChainSignals,
    WorkflowPlannerStepSignals,
    WorkflowAssessRoutingHintSignals,
    WorkflowToolClarificationSignals,
    WorkflowTerminalActionSignals,
    WorkflowRefinementSignals,
    WorkflowReviewParseFailureSignals,
    BoundedReviewAssessDecision,
    BoundedReviewAssessCoreSignals,
    AssessTraceAlignmentSignals,
    BoundedReviewAssessSignals,
    StepOutcome,
    StepRecord,
    WorkflowRecord,
    EvaluatorAuthorityLevel,
    WorkflowModeId,
    WorkflowModeSelectionSource,
    WorkflowModeEvidencePosture,
    WorkflowModeExecutionPresetId,
    WorkflowProfileClass,
    WorkflowProfileId,
    WorkflowExecutionPolicy,
    WorkflowReviewPassMode,
    WorkflowReviseStepMode,
    WorkflowModeBehavior,
    WorkflowModeDecision,
    ReviewRuntimeLabel,
    ReviewRuntimeSummary,
    ReviewIntensity,
    SteerabilityControlId,
    SteerabilityControlSource,
    SteerabilityImpactTarget,
    SteerabilityControlRecord,
    SteerabilityControls,
    ProviderPreferenceOutcomeState,
    ToolAllowanceState,
    GroundingEvidenceStatus,
    EvaluatorDecisionMode,
    SafetyAction,
    SafetyReasonCode,
    SafetyEvaluationInput,
    SafetyEvaluationResult,
    SafetyDecision,
    EvaluatorOutcome,
    ExecutionEvent,
    TrustGraphMetadata,
    ImageGenerationMetadata,
    GitHubContextMetadata,
    GitHubContextSection,
    ResponseMetadata,
} from './types.js';
export type {
    ResponseFootnote,
    ResponseFootnoteSection,
} from './responseFootnote.js';
export { RESPONSE_FOOTNOTE_SECTIONS } from './responseFootnote.js';
export {
    WORKFLOW_STEP_STATUSES,
    WORKFLOW_STEP_KINDS,
    WORKFLOW_TERMINATION_REASONS,
    WORKFLOW_LIMIT_KEYS,
    WORKFLOW_LIMIT_STATES,
    WORKFLOW_MODE_EXECUTION_PRESET_IDS,
    WORKFLOW_PROFILE_CLASSES,
    WORKFLOW_PROFILE_IDS,
    WORKFLOW_EXECUTION_POLICIES,
    WORKFLOW_REVIEW_PASS_MODES,
    WORKFLOW_REVISE_STEP_MODES,
    WORKFLOW_EVIDENCE_POSTURES,
    BOUNDED_REVIEW_ASSESS_DECISIONS,
    TRACE_TEMPERAMENT_AXIS_KEYS,
    TRACE_ASSESS_FINAL_TEMPERAMENT_SIGNAL_KEYS,
    TRACE_PLANNER_TARGET_TEMPERAMENT_SIGNAL_KEYS,
    isTraceTemperamentEqual,
    REVIEW_RUNTIME_LABELS,
    REVIEW_INTENSITY_LEVELS,
    PROVIDER_PREFERENCE_OUTCOME_STATES,
    TOOL_ALLOWANCE_STATES,
    GROUNDING_EVIDENCE_STATUSES,
} from './types.js';
export { CONTEXT_INTEGRATION_NAMES } from './contextIntegrations.js';
export type { ContextIntegrationName } from './contextIntegrations.js';
export {
    PROJECT_CONTEXT_CATEGORIES,
    PROJECT_CONTEXT_CANONICAL_REPOSITORY,
    type ProjectContextCategory,
    type ProjectContextMatch,
    type ProjectContextMetadata,
    type ProjectContextReasonCode,
} from './projectContext.js';
export { formatExecutionTimelineSummary } from './executionFormatting.js';
export {
    buildContextPresentationSummary,
    formatGitHubContextSummary,
    formatProjectContextSummary,
} from './contextPresentation.js';
export { deriveReviewRuntimeSummary } from './reviewRuntime.js';
export {
    buildWorkflowRoutingChainSignals,
    buildWorkflowAssessRoutingHintSignals,
    buildWorkflowReviewParseFailureSignals,
    isPlannerFallbackStep,
    isRefinementGenerateStep,
    getWorkflowStepProfileIdSignal,
    getPlannerStepContractType,
} from './workflowStepSignals.js';
export {
    resolveReviewReceipt,
    resolvePlannerFallbackReceipt,
    resolvePresentationReceipt,
    summarizeGroundingEvidence,
    buildWorkflowReceiptItems,
    buildWorkflowReceiptSummary,
    WORKFLOW_RECEIPT_LABELS,
} from './workflowReceipt.js';
export type { GroundingEvidenceSummary } from './workflowReceipt.js';
export {
    SafetyRuleIdSchema,
    SafetyActionSchema,
    SafetyReasonCodeSchema,
    SafetyDecisionSchema,
} from './schemas.js';
export {
    SAFETY_RULE_METADATA,
    type SafetyRuleMetadata,
} from './safetyRuleMetadata.js';
export {
    resolveBreakerDecisionContext,
    type BreakerDecisionSource,
    type BreakerDecisionContext,
} from './breakerDecision.js';
